var mongoose = require("mongoose");
var models = require("./data/models");
var Promise = require("bluebird");
var moment = require("moment");

var issues = [
	{ name: "Add progress indicator for changing pages", number: "45", isDeleted: 0, opened: "Mar 11 2014 12:00AM", closed: "", updated: "Mar 12 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "High", status: "Complete", milestone: "Version 1", type: "Feature", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Set default values for choice tiles on the create issue page", number: "9", isDeleted: 0, opened: "Feb 23 2014 12:00AM", closed: "", updated: "Mar 11 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "High", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Remove the \"add comment\" button", number: "51", isDeleted: 0, opened: "Mar 10 2014 12:00AM", closed: "Mar 12 2014  3:02PM", updated: "Mar 12 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Defect", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Clear create issue page's fields after issue is saved", number: "5", isDeleted: 0, opened: "Feb 24 2014 12:00AM", closed: "", updated: "Mar 11 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 2", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Create CSS3 spinner, and associated fallback", number: "18", isDeleted: 0, opened: "Feb 24 2014 12:00AM", closed: "", updated: "Feb 24 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Low", status: "Pending Development", milestone: "Backlog", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Add attached file section on issue details page", number: "16", isDeleted: 0, opened: "Feb 16 2014 12:00AM", closed: "", updated: "Mar 12 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Pending Development", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Limit width of app to 1680 pixels", number: "53", isDeleted: 0, opened: "Mar 10 2014 12:00AM", closed: "Mar 12 2014  5:01PM", updated: "Mar 12 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "High", status: "Complete", milestone: "Version 1", type: "Feature", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Added comment and existing comment times are in different timezones", number: "7", isDeleted: 0, opened: "Mar 10 2014 12:00AM", closed: "", updated: "Mar 11 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Defect", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Add animation for issue list", number: "56", isDeleted: 0, opened: "Mar 12 2014 12:00AM", closed: "", updated: "Mar 12 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Medium", status: "Pending Development", milestone: "Version 1", type: "Feature", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Build user management page", number: "3", isDeleted: 0, opened: "Feb 24 2014 12:00AM", closed: "", updated: "Mar 12 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "test", number: "1", isDeleted: 0, opened: "Feb 23 2014 12:00AM", closed: "", updated: "Feb 23 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Add page transitions", number: "32", isDeleted: 0, opened: "Feb 27 2014 12:00AM", closed: "Mar 12 2014  2:47AM", updated: "Mar 11 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Create wrapper for jStorage", number: "37", isDeleted: 0, opened: "Mar  5 2014 12:00AM", closed: "", updated: "Mar  5 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Low", status: "Pending Development", milestone: "Backlog", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Issue should automatically save when the user has clicked a transition button", number: "29", isDeleted: 0, opened: "Feb 26 2014 12:00AM", closed: "Mar 12 2014  2:30AM", updated: "Mar 11 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "High", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "blah", number: "2", isDeleted: 0, opened: "Feb 23 2014 12:00AM", closed: "", updated: "Feb 23 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Low", status: "Pending Development", milestone: "Backlog", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Add loading indicator for updating issues list", number: "43", isDeleted: 0, opened: "Mar  6 2014 12:00AM", closed: "", updated: "Mar 11 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Defect", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "test", number: "57", isDeleted: 0, opened: "Mar 11 2014 12:00AM", closed: "", updated: "Mar 11 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Low", status: "Pending Development", milestone: "Backlog", type: "Defect", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Save current filter settings and restore them on page load", number: "28", isDeleted: 0, opened: "Feb 27 2014 12:00AM", closed: "", updated: "Feb 28 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "High", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Filters on the list page only allow the user to make one selection", number: "11", isDeleted: 0, opened: "Feb 24 2014 12:00AM", closed: "", updated: "Feb 28 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "\"Comments\" on the create issue page should be changed to \"Detailed description\"", number: "34", isDeleted: 0, opened: "Feb 28 2014 12:00AM", closed: "", updated: "Mar  5 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Build header menu", number: "44", isDeleted: 0, opened: "Mar  7 2014 12:00AM", closed: "", updated: "Mar 11 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Feature", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Add fade animation for issue details in collapsed view", number: "46", isDeleted: 0, opened: "Mar 11 2014 12:00AM", closed: "", updated: "Mar 11 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Low", status: "Pending Development", milestone: "Version 1", type: "Feature", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "The \"no issues\" container shouldn't show up while issues are being loaded", number: "48", isDeleted: 0, opened: "Mar 10 2014 12:00AM", closed: "Mar 12 2014  8:03PM", updated: "Mar 12 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Defect", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Add email issue functionality", number: "27", isDeleted: 0, opened: "Feb 25 2014 12:00AM", closed: "", updated: "Feb 25 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Pending Development", milestone: "Backlog", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Add sorting to issues list page", number: "24", isDeleted: 0, opened: "Feb 25 2014 12:00AM", closed: "", updated: "Feb 28 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Add description/comments search", number: "31", isDeleted: 0, opened: "Feb 26 2014 12:00AM", closed: "", updated: "Mar 12 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "High", status: "Pending Development", milestone: "Version 2", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "When no filters are set, should show filters as \"all\"", number: "30", isDeleted: 0, opened: "Feb 28 2014 12:00AM", closed: "", updated: "Feb 28 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Medium", status: "Pending Development", milestone: "Backlog", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Focus on \"issue details\" field when navigating to the create issue page", number: "21", isDeleted: 0, opened: "Feb 24 2014 12:00AM", closed: "", updated: "Mar 11 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Medium", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Add popup to show more detailed issue information when hovering", number: "41", isDeleted: 0, opened: "Mar  5 2014 12:00AM", closed: "", updated: "Mar  6 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Feature", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Widen the create issue button", number: "15", isDeleted: 0, opened: "Feb 24 2014 12:00AM", closed: "", updated: "Feb 24 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Medium", status: "Pending Development", milestone: "Backlog", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Add indicator icons to issue rows on the issues page", number: "23", isDeleted: 0, opened: "Feb 25 2014 12:00AM", closed: "", updated: "Feb 25 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Medium", status: "Pending Development", milestone: "Backlog", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Add advanced text editor functions for comments and detailed descriptions", number: "35", isDeleted: 0, opened: "Feb 28 2014 12:00AM", closed: "", updated: "Feb 28 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Medium", status: "Pending Development", milestone: "Backlog", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Add toggle between views", number: "25", isDeleted: 0, opened: "Feb 25 2014 12:00AM", closed: "", updated: "Mar  5 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "The height of each choice tile on the create issue page should be equal", number: "13", isDeleted: 0, opened: "Feb 24 2014 12:00AM", closed: "", updated: "Feb 24 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Low", status: "Pending Development", milestone: "Backlog", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "test feature", number: "39", isDeleted: 0, opened: "Mar  5 2014 12:00AM", closed: "", updated: "Mar  5 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Low", status: "Pending Development", milestone: "Backlog", type: "Feature", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Hook up the attached files section on the create issue page", number: "14", isDeleted: 0, opened: "Feb 22 2014 12:00AM", closed: "", updated: "Mar 12 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Pending Development", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "The \"save new issue\" button doesn't have loading styles applied when clicked", number: "22", isDeleted: 0, opened: "Feb 25 2014 12:00AM", closed: "", updated: "Feb 28 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "High", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "IssuesController.Next should return serialized IssueViewModels", number: "19", isDeleted: 0, opened: "Feb 25 2014 12:00AM", closed: "", updated: "Feb 25 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Medium", status: "Pending Development", milestone: "Backlog", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Disable session timeout for logged in user", number: "20", isDeleted: 0, opened: "Feb 25 2014 12:00AM", closed: "", updated: "Feb 28 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Change hover colour", number: "52", isDeleted: 0, opened: "Mar 11 2014 12:00AM", closed: "Mar 12 2014  7:53PM", updated: "Mar 12 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "High", status: "Complete", milestone: "Version 1", type: "Defect", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Deleting an issue sets its project ID to null", number: "40", isDeleted: 0, opened: "Mar  5 2014 12:00AM", closed: "", updated: "Mar  5 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Defect", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Most datetimes in the application have the time portion set to 12:00:00", number: "42", isDeleted: 0, opened: "Mar  4 2014 12:00AM", closed: "Mar 12 2014  2:31AM", updated: "Mar 11 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "High", status: "Complete", milestone: "Version 1", type: "Defect", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Progress bar fires when focusing back on the window even when not on the issues page", number: "54", isDeleted: 0, opened: "Mar 11 2014 12:00AM", closed: "Mar 12 2014  8:02PM", updated: "Mar 12 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "High", status: "Complete", milestone: "Version 1", type: "Defect", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Add issue type", number: "4", isDeleted: 0, opened: "Feb 24 2014 12:00AM", closed: "", updated: "Mar  5 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Feature", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Cache issue list", number: "50", isDeleted: 0, opened: "Mar 10 2014 12:00AM", closed: "Mar 12 2014  3:42PM", updated: "Mar 12 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Defect", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "The issue list's individual issue tiles are misaligned in Firefox", number: "8", isDeleted: 0, opened: "Feb 24 2014 12:00AM", closed: "", updated: "Feb 28 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Add audit trail section to issue details page", number: "17", isDeleted: 0, opened: "Feb 24 2014 12:00AM", closed: "", updated: "Mar  7 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Look into faster methods of choosing data on the issue details page", number: "55", isDeleted: 0, opened: "Mar 12 2014 12:00AM", closed: "", updated: "Mar 12 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Medium", status: "Pending Development", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "test defect", number: "38", isDeleted: 0, opened: "Mar  5 2014 12:00AM", closed: "", updated: "Mar  5 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Low", status: "Pending Development", milestone: "Backlog", type: "Defect", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Hook up date closed property", number: "10", isDeleted: 0, opened: "Feb 23 2014 12:00AM", closed: "Mar 12 2014  2:30AM", updated: "Mar 11 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "High", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Remove the \"updated\" field from the issue audit trail", number: "36", isDeleted: 0, opened: "Mar  3 2014 12:00AM", closed: "", updated: "Mar 11 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "High", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Add global error \"page\"", number: "49", isDeleted: 0, opened: "Mar  8 2014 12:00AM", closed: "Mar 12 2014  6:46PM", updated: "Mar 12 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Complete", milestone: "Version 1", type: "Feature", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Increase font size for description on the create issue page", number: "7", isDeleted: 0, opened: "Feb 24 2014 12:00AM", closed: "", updated: "Feb 24 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Medium", status: "Pending Development", milestone: "Backlog", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Issue details URL should show number instead of description", number: "33", isDeleted: 0, opened: "Feb 27 2014 12:00AM", closed: "", updated: "Mar 11 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "High", status: "Complete", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Add issue number to list", number: "6", isDeleted: 0, opened: "Feb 23 2014 12:00AM", closed: "", updated: "Mar 11 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "High", status: "Complete", milestone: "Version 1", type: "Feature", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Remove blue highlight from focused issue description and comments on create issue page", number: "26", isDeleted: 0, opened: "Feb 25 2014 12:00AM", closed: "", updated: "Feb 25 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Medium", status: "Pending Development", milestone: "Backlog", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
	{ name: "Build project management page", number: "12", isDeleted: 0, opened: "Feb 24 2014 12:00AM", closed: "", updated: "Mar  5 2014 12:00AM", developer: "Chris Harrington", tester: "Chris Harrington", priority: "Critical", status: "Pending Development", milestone: "Version 1", type: "Investigation", project: "Unnamed Issue Tracker", updatedBy: "Chris Harrington" },
];

var user, project, priorities, statuses, milestones, types;
require("./data/connection").open().then(function() {
	return [models.User.findOneAsync(), models.Project.findOneAsync()];
}).spread(function(u, p) {
	project = p;
	user = u;
	return models.Issue.removeAsync();
}).then(function() {
	return [models.Priority.findAsync(), models.Status.findAsync(), models.Milestone.findAsync(), models.IssueType.findAsync()];
}).spread(function(p, s, m, it) {
	priorities = _toObject(p);
	statuses = _toObject(s);
	milestones = _toObject(m);
	types = _toObject(it);
	for (var i = 0; i < issues.length; i++) {
		issues[i].developer = issues[i].tester = issues[i].updatedBy = user._id;
		issues[i].project = project._id;
		issues[i].priority = priorities[issues[i].priority.toLowerCase()]._id;
		issues[i].status = statuses[issues[i].status.toLowerCase()]._id;
		issues[i].milestone = milestones[issues[i].milestone.toLowerCase()]._id;
		issues[i].type = types[issues[i].type.toLowerCase()]._id;
		issues[i].opened = _formatDate(issues[i].opened);
		issues[i].closed = _formatDate(issues[i].closed);
		issues[i].updated = _formatDate(issues[i].updated);
		issues[i] = new models.Issue(issues[i]).save(function(err) {
			console.log(err);
		});
	}
	return issues;
}).then(function() {
	console.log("Done!");
}).catch(function(e) {
	console.log("Error: " + e);
});

function _toObject(array) {
	var result = {};
	for (var i = 0; i < array.length; i++)
		result[array[i].name.toLowerCase()] = array[i]._id;
	return result;
}

function _formatDate(date) {
	return date ? moment(date, "MMM DD YYYY h:mmA") : null;
}

//"Feb 24 2014 12:00AM"