// <auto-generated />
namespace IssueTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class EnableRequiredIssueTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnableRequiredIssueTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201403052128143_enabled-required-issue-types"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
